### ISSUE TITLE
DMA test error 

### ISSUE THREAD

**Issue by hanm2019** [IBM/esp-chisel-accelerators#42]
when I run the DmaSpec testcase, it come out the error:
```
[info] DmaSpec:
[info] QuickFPS.Dma
[info] DmaSpec *** ABORTED ***
[info]   java.lang.NoSuchMethodError: treadle.TreadleTester.<init>(Ljava/lang/String;Ltreadle/HasTreadleSuite;Lfirrtl/CircuitForm;)V
[info]   at chisel3.iotesters.TreadleBackend.<init>(TreadleBackend.scala:17)
[info]   at chisel3.iotesters.setupTreadleBackend$.apply(TreadleBackend.scala:147)
[info]   at chisel3.iotesters.Driver$.$anonfun$execute$2(Driver.scala:53)
[info]   at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
[info]   at logger.Logger$.$anonfun$makeScope$2(Logger.scala:166)
[info]   at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[info]   at logger.Logger$.makeScope(Logger.scala:164)
[info]   at logger.Logger$.makeScope(Logger.scala:127)
[info]   at chisel3.iotesters.Driver$.$anonfun$execute$1(Driver.scala:38)
[info]   at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
[info]   ...
```

It seem that some class has problem with running time, since I can generate .v file.

**Comment by hanm2019** [comment]
the [sample case](https://github.com/hanm2019/sample_case) with Dma
